/**
 * Turns the hand-written manifests in registry/*.ts into every generated
 * artifact the site and the shadcn CLI need:
 *
 *   registry/__index__.tsx  -> lazy component map used by <ComponentPreview />
 *   registry.json           -> single-file registry consumed by `shadcn build`
 *   public/r/<name>.json    -> what `npx shadcn add @loomui/<name>` fetches
 *   public/llms.txt         -> link index for LLMs
 *   public/llms-full.txt    -> every component's source, inlined
 *
 * All outputs are committed; CI re-runs this and fails on drift.
 */
import { exec } from "node:child_process"
import { promises as fs } from "node:fs"
import path from "node:path"
import process from "node:process"
import { fileURLToPath } from "node:url"
import { promisify } from "node:util"
import type { Registry } from "shadcn/schema"

import { siteConfig } from "../config/site.ts"
import {
  assertNoMissingExampleFiles,
  syncExampleRegistryDependencies,
} from "./sync-example-registry-dependencies.mts"

const execAsync = promisify(exec)

const scriptPath = fileURLToPath(import.meta.url)
const appRoot = path.resolve(path.dirname(scriptPath), "..")
const registryRoot = path.join(appRoot, "registry")
const publicRoot = path.join(appRoot, "public")

type RegistryItem = Registry["items"][number]

const toPosix = (value: string) => value.split(path.sep).join("/")

async function loadRegistry(): Promise<Registry> {
  const { buildRegistry } = await import("../registry/index.ts")
  return buildRegistry()
}

/**
 * The lazy import lets the docs render a live demo from the same file the code
 * tab shows, so a preview can never drift from its source.
 */
/** Item types that can actually be rendered as a live preview. */
const RENDERABLE = new Set([
  "registry:ui",
  "registry:example",
  "registry:component",
  "registry:block",
])

async function buildRegistryIndex(registry: Registry) {
  const entries = registry.items.map((item) => {
    // Paths stay repo-relative so the generated file is identical on every
    // machine, since CI compares this artifact byte for byte.
    const files = (item.files ?? []).map((file) => ({
      path: `registry/${toPosix(file.path)}`,
      type: file.type,
      target: file.target ?? "",
    }))

    const first = item.files?.[0]?.path
    const componentImport =
      first && RENDERABLE.has(item.type)
        ? `@/registry/${toPosix(first).replace(/\.tsx?$/, "")}`
        : null

    const component = componentImport
      ? `React.lazy(async () => {
      const mod = await import("${componentImport}")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    })`
      : "null"

    return `  ${JSON.stringify(item.name)}: {
    name: ${JSON.stringify(item.name)},
    type: ${JSON.stringify(item.type)},
    title: ${JSON.stringify(item.title ?? item.name)},
    description: ${JSON.stringify(item.description ?? "")},
    dependencies: ${JSON.stringify(item.dependencies ?? [])},
    registryDependencies: ${JSON.stringify(item.registryDependencies ?? [])},
    files: ${JSON.stringify(files)},
    component: ${component},
  },`
  })

  const contents = `/* eslint-disable */
// @ts-nocheck
// AUTOGENERATED by scripts/build-registry.mts - do not edit.
import * as React from "react"

export const Index: Record<string, any> = {
${entries.join("\n")}
}
`

  await fs.writeFile(path.join(registryRoot, "__index__.tsx"), contents, "utf8")
}

/**
 * `shadcn build` resolves file paths relative to the working directory, so the
 * on-disk manifest prefixes them with `registry/` while the authored manifests
 * stay registry-relative.
 */
async function buildRegistryJson(registry: Registry) {
  const resolved = {
    ...registry,
    items: registry.items.map((item) => ({
      ...item,
      files: item.files?.map((file) => ({
        ...file,
        path: `registry/${toPosix(file.path)}`,
      })),
    })),
  }

  const json = `${JSON.stringify(resolved, null, 2)}\n`

  await fs.writeFile(path.join(appRoot, "registry.json"), json, "utf8")
  await fs.mkdir(publicRoot, { recursive: true })
  await fs.writeFile(path.join(publicRoot, "registry.json"), json, "utf8")
}

async function readItemSources(item: RegistryItem) {
  const files = [...(item.files ?? [])].sort((a, b) =>
    a.path.localeCompare(b.path)
  )

  const chunks = await Promise.all(
    files.map(async (file) => {
      try {
        const content = await fs.readFile(
          path.join(registryRoot, file.path),
          "utf8"
        )
        return `--- file: ${toPosix(file.path)} ---\n${content.trimEnd()}\n`
      } catch {
        return null
      }
    })
  )

  return chunks.filter(Boolean).join("\n")
}

/** component name -> example names that depend on it */
function groupExamplesByComponent(registry: Registry) {
  const byComponent = new Map<string, string[]>()

  for (const item of registry.items) {
    if (item.type !== "registry:example") continue

    for (const dependency of item.registryDependencies ?? []) {
      const component = dependency.split("/").pop()
      if (!component) continue
      byComponent.set(component, [
        ...(byComponent.get(component) ?? []),
        item.name,
      ])
    }
  }

  return byComponent
}

function buildLlmsIndex(registry: Registry) {
  const components = registry.items
    .filter((item) => item.type === "registry:ui")
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((item) => {
      const title = item.title ?? item.name
      const description = item.description ?? `The ${title} component.`
      return `- [${title}](${siteConfig.url}/docs/components/${item.name}): ${description}`
    })

  return [
    `# ${siteConfig.name}`,
    "",
    `> ${siteConfig.description}`,
    "",
    `Install any component with \`npx shadcn@latest add ${siteConfig.registry.namespace}/<name>\`.`,
    "",
    "## Components",
    "",
    ...components,
    "",
    "## Links",
    "",
    `- [Registry](${siteConfig.registry.url}/registry.json): Machine-readable index`,
    `- [Repository](${siteConfig.links.github}): Source and issues`,
  ].join("\n")
}

async function buildLlmsFull(registry: Registry) {
  const examplesByComponent = groupExamplesByComponent(registry)
  const components = registry.items
    .filter((item) => item.type === "registry:ui")
    .sort((a, b) => a.name.localeCompare(b.name))

  const sections = await Promise.all(
    components.map(async (component) => {
      const parts = [
        `===== COMPONENT: ${component.name} =====`,
        `Title: ${component.title ?? component.name}`,
        `Description: ${component.description ?? ""}`,
        `Install: npx shadcn@latest add ${siteConfig.registry.namespace}/${component.name}`,
        "",
        await readItemSources(component),
      ]

      for (const exampleName of examplesByComponent.get(component.name) ?? []) {
        const example = registry.items.find((item) => item.name === exampleName)
        if (!example) continue

        parts.push(
          "",
          `===== EXAMPLE: ${example.name} =====`,
          `Title: ${example.title ?? example.name}`,
          "",
          await readItemSources(example)
        )
      }

      return parts.join("\n")
    })
  )

  return sections.join("\n\n")
}

async function buildLlmsFiles(registry: Registry) {
  await fs.mkdir(publicRoot, { recursive: true })

  await Promise.all([
    fs.writeFile(path.join(publicRoot, "llms.txt"), buildLlmsIndex(registry), "utf8"),
    fs.writeFile(
      path.join(publicRoot, "llms-full.txt"),
      await buildLlmsFull(registry),
      "utf8"
    ),
  ])
}

async function buildItemJsonFiles() {
  const { stdout, stderr } = await execAsync(
    "pnpm registry:shadcn",
    { cwd: appRoot }
  )
  if (stdout.trim()) console.log(stdout.trim())
  if (stderr.trim()) console.error(stderr.trim())
}

async function main() {
  console.log("Syncing example registry dependencies...")
  const issues = await syncExampleRegistryDependencies({ mode: "fix" })
  assertNoMissingExampleFiles(issues)

  const registry = await loadRegistry()

  console.log("Writing registry/__index__.tsx...")
  await buildRegistryIndex(registry)

  console.log("Writing registry.json...")
  await buildRegistryJson(registry)

  console.log("Writing llms.txt / llms-full.txt...")
  await buildLlmsFiles(registry)

  console.log("Building public/r/*.json...")
  await buildItemJsonFiles()

  console.log(`Registry built: ${registry.items.length} items`)
}

try {
  await main()
} catch (error) {
  console.error("Registry build failed")
  console.error(error)
  process.exit(1)
}
