/* eslint-disable */
// @ts-nocheck
// AUTOGENERATED by scripts/build-registry.mts - do not edit.
import * as React from "react"

export const Index: Record<string, any> = {
  "weave-text": {
    name: "weave-text",
    type: "registry:ui",
    title: "Weave Text",
    description: "Text filled with a slow-drifting gradient, woven from a palette you control.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/weave-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/weave-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "stagger-text": {
    name: "stagger-text",
    type: "registry:ui",
    title: "Stagger Text",
    description: "Words or characters that rise into place one after another, on mount or on scroll.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/stagger-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/stagger-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "typewriter": {
    name: "typewriter",
    type: "registry:ui",
    title: "Typewriter",
    description: "Phrases typed out and deleted in a loop, with a caret and no layout shift.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/typewriter.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/typewriter")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "scramble-text": {
    name: "scramble-text",
    type: "registry:ui",
    title: "Scramble Text",
    description: "A string that resolves out of random glyphs, left to right, on mount, on scroll, or on hover.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/scramble-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/scramble-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "count-up": {
    name: "count-up",
    type: "registry:ui",
    title: "Count Up",
    description: "A number that counts to its value when it scrolls into view, without a render per frame.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/count-up.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/count-up")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "lens-text": {
    name: "lens-text",
    type: "registry:ui",
    title: "Lens Text",
    description: "Text held out of focus until the pointer passes over it like a magnifying glass.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/lens-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/lens-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-backdrop": {
    name: "grid-backdrop",
    type: "registry:ui",
    title: "Grid Backdrop",
    description: "An SVG grid with cells that fade in and out at a deterministic, seeded scatter.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/grid-backdrop.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/grid-backdrop")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "spotlight-card": {
    name: "spotlight-card",
    type: "registry:ui",
    title: "Spotlight Card",
    description: "A surface with a soft highlight that follows the pointer and fades out on leave.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/spotlight-card.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/spotlight-card")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-beams": {
    name: "grid-beams",
    type: "registry:ui",
    title: "Grid Beams",
    description: "A ruled grid with neon beams running down random lines, fading out toward the edges.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/grid-beams.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/grid-beams")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "aurora-backdrop": {
    name: "aurora-backdrop",
    type: "registry:ui",
    title: "Aurora Backdrop",
    description: "A wash of blurred colour that drifts behind content on cycles that never line up.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/aurora-backdrop.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/aurora-backdrop")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "tilt-card": {
    name: "tilt-card",
    type: "registry:ui",
    title: "Tilt Card",
    description: "A surface that leans away from the pointer in 3D and settles back on leave.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/tilt-card.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/tilt-card")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "magnetic": {
    name: "magnetic",
    type: "registry:ui",
    title: "Magnetic",
    description: "A wrapper that pulls its child toward the pointer as the pointer gets close.",
    dependencies: ["@radix-ui/react-slot"],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/magnetic.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/magnetic")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "marquee": {
    name: "marquee",
    type: "registry:ui",
    title: "Marquee",
    description: "A seamless scrolling row or column, in either direction, that pauses on hover.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/marquee.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/marquee")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "reading-progress": {
    name: "reading-progress",
    type: "registry:ui",
    title: "Reading Progress",
    description: "A pinned bar that tracks how far through the page, or a chosen element, the reader is.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/reading-progress.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/reading-progress")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "weave-text-demo": {
    name: "weave-text-demo",
    type: "registry:example",
    title: "Weave Text Demo",
    description: "Weave Text used as a headline accent.",
    dependencies: [],
    registryDependencies: ["@loomui/weave-text"],
    files: [{"path":"registry/example/weave-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/weave-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "stagger-text-demo": {
    name: "stagger-text-demo",
    type: "registry:example",
    title: "Stagger Text Demo",
    description: "A sentence revealed word by word when it scrolls into view.",
    dependencies: [],
    registryDependencies: ["@loomui/stagger-text"],
    files: [{"path":"registry/example/stagger-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/stagger-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "typewriter-demo": {
    name: "typewriter-demo",
    type: "registry:example",
    title: "Typewriter Demo",
    description: "A rotating list of phrases typed into a fixed-width slot.",
    dependencies: [],
    registryDependencies: ["@loomui/typewriter"],
    files: [{"path":"registry/example/typewriter-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/typewriter-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "scramble-text-demo": {
    name: "scramble-text-demo",
    type: "registry:example",
    title: "Scramble Text Demo",
    description: "A wordmark decoding out of noise on every hover.",
    dependencies: [],
    registryDependencies: ["@loomui/scramble-text"],
    files: [{"path":"registry/example/scramble-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/scramble-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "count-up-demo": {
    name: "count-up-demo",
    type: "registry:example",
    title: "Count Up Demo",
    description: "Three statistics counting to their values in step.",
    dependencies: [],
    registryDependencies: ["@loomui/count-up"],
    files: [{"path":"registry/example/count-up-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/count-up-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "lens-text-demo": {
    name: "lens-text-demo",
    type: "registry:example",
    title: "Lens Text Demo",
    description: "A blurred paragraph read through a lens at the pointer.",
    dependencies: [],
    registryDependencies: ["@loomui/lens-text"],
    files: [{"path":"registry/example/lens-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/lens-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-backdrop-demo": {
    name: "grid-backdrop-demo",
    type: "registry:example",
    title: "Grid Backdrop Demo",
    description: "A grid pulsing behind a headline.",
    dependencies: [],
    registryDependencies: ["@loomui/grid-backdrop"],
    files: [{"path":"registry/example/grid-backdrop-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-backdrop-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "spotlight-card-demo": {
    name: "spotlight-card-demo",
    type: "registry:example",
    title: "Spotlight Card Demo",
    description: "Two cards lit by the pointer as it crosses them.",
    dependencies: [],
    registryDependencies: ["@loomui/spotlight-card"],
    files: [{"path":"registry/example/spotlight-card-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/spotlight-card-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-beams-demo": {
    name: "grid-beams-demo",
    type: "registry:example",
    title: "Grid Beams Demo",
    description: "Neon beams running down a ruled grid behind a panel of copy.",
    dependencies: [],
    registryDependencies: ["@loomui/grid-beams"],
    files: [{"path":"registry/example/grid-beams-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-beams-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "aurora-backdrop-demo": {
    name: "aurora-backdrop-demo",
    type: "registry:example",
    title: "Aurora Backdrop Demo",
    description: "A drifting colour wash behind a panel of copy.",
    dependencies: [],
    registryDependencies: ["@loomui/aurora-backdrop"],
    files: [{"path":"registry/example/aurora-backdrop-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/aurora-backdrop-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "tilt-card-demo": {
    name: "tilt-card-demo",
    type: "registry:example",
    title: "Tilt Card Demo",
    description: "A card that leans away from the pointer with a soft sheen.",
    dependencies: [],
    registryDependencies: ["@loomui/tilt-card"],
    files: [{"path":"registry/example/tilt-card-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/tilt-card-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "magnetic-demo": {
    name: "magnetic-demo",
    type: "registry:example",
    title: "Magnetic Demo",
    description: "A button that leans toward the pointer.",
    dependencies: [],
    registryDependencies: ["@loomui/magnetic"],
    files: [{"path":"registry/example/magnetic-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/magnetic-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "marquee-demo": {
    name: "marquee-demo",
    type: "registry:example",
    title: "Marquee Demo",
    description: "A row of quote cards scrolling on a seamless loop.",
    dependencies: [],
    registryDependencies: ["@loomui/marquee"],
    files: [{"path":"registry/example/marquee-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/marquee-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "reading-progress-demo": {
    name: "reading-progress-demo",
    type: "registry:example",
    title: "Reading Progress Demo",
    description: "The page-level progress bar, live at the top of the screen.",
    dependencies: [],
    registryDependencies: ["@loomui/reading-progress"],
    files: [{"path":"registry/example/reading-progress-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/reading-progress-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "utils": {
    name: "utils",
    type: "registry:lib",
    title: "Utils",
    description: "The cn() class merge helper every loom component depends on.",
    dependencies: ["clsx","tailwind-merge"],
    registryDependencies: [],
    files: [{"path":"registry/lib/utils.ts","type":"registry:lib","target":""}],
    component: null,
  },
}
