/* eslint-disable */
// @ts-nocheck
// AUTOGENERATED by scripts/build-registry.mts - do not edit.
import * as React from "react"

export const Index: Record<string, any> = {
  "theme": {
    name: "theme",
    type: "registry:theme",
    title: "loom design tokens",
    description: "The whole token layer: colour for both themes, the type scale with its paired line height and letter spacing, elevation, blur, the stacking scale, durations and easing curves. Install this for loom's design system without any particular component.",
    dependencies: [],
    registryDependencies: [],
    categories: [],
    files: [],
    component: null,
  },
  "analytics-dashboard": {
    name: "analytics-dashboard",
    type: "registry:block",
    title: "Analytics Dashboard",
    description: "A dashboard built from loom's charts: four counted stats, a stacked trend, a source gauge and an onboarding funnel, with a range control that replays the reveal.",
    dependencies: [],
    registryDependencies: ["@loomui/bento-grid","@loomui/count-up","@loomui/elastic-tabs","@loomui/funnel-rows","@loomui/gauge-arc","@loomui/trend-stack"],
    categories: ["dashboard"],
    files: [{"path":"registry/blocks/analytics-dashboard.tsx","type":"registry:block","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/analytics-dashboard")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "onboarding-flow": {
    name: "onboarding-flow",
    type: "registry:block",
    title: "Onboarding Flow",
    description: "A setup checklist with a progress ring, morphing tick marks, a drawer of answers, and a finish button that only celebrates once every step is done.",
    dependencies: [],
    registryDependencies: ["@loomui/confetti-button","@loomui/drawer","@loomui/icon-morph","@loomui/progress-ring","@loomui/unfold-list"],
    categories: ["onboarding"],
    files: [{"path":"registry/blocks/onboarding-flow.tsx","type":"registry:block","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/onboarding-flow")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "login-form": {
    name: "login-form",
    type: "registry:block",
    title: "Login",
    description: "A split sign-in screen. The submit button changes shape through idle, working and done rather than swapping a label for a spinner.",
    dependencies: [],
    registryDependencies: ["@loomui/icon-morph","@loomui/light-curtain","@loomui/ripple-button","@loomui/shake-field","@loomui/spool","@loomui/weave-text"],
    categories: ["authentication"],
    files: [{"path":"registry/blocks/login-form.tsx","type":"registry:block","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/login-form")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "signup-form": {
    name: "signup-form",
    type: "registry:block",
    title: "Signup",
    description: "A sign-up screen with a password meter driven by a spring, so each keystroke retargets the ring rather than queueing behind the last one.",
    dependencies: [],
    registryDependencies: ["@loomui/confetti-button","@loomui/icon-morph","@loomui/progress-ring","@loomui/shake-field","@loomui/unfold-list"],
    categories: ["authentication"],
    files: [{"path":"registry/blocks/signup-form.tsx","type":"registry:block","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/signup-form")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "weave-text": {
    name: "weave-text",
    type: "registry:ui",
    title: "Weave Text",
    description: "Text filled with a slow-drifting gradient, woven from a palette you control.",
    dependencies: [],
    registryDependencies: ["utils","use-in-viewport"],
    categories: [],
    files: [{"path":"registry/loomui/weave-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/weave-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "stagger-text": {
    name: "stagger-text",
    type: "registry:ui",
    title: "Stagger Text",
    description: "Words or characters that rise into place one after another, on mount or on scroll.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/stagger-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/stagger-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "typewriter": {
    name: "typewriter",
    type: "registry:ui",
    title: "Typewriter",
    description: "Phrases typed out and deleted in a loop, with a caret and no layout shift.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/typewriter.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/typewriter")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "scramble-text": {
    name: "scramble-text",
    type: "registry:ui",
    title: "Scramble Text",
    description: "A string that resolves out of random glyphs, left to right, on mount, on scroll, or on hover.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/scramble-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/scramble-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "count-up": {
    name: "count-up",
    type: "registry:ui",
    title: "Count Up",
    description: "A number that counts to its value when it scrolls into view, without a render per frame.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/count-up.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/count-up")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "lens-text": {
    name: "lens-text",
    type: "registry:ui",
    title: "Lens Text",
    description: "Text held out of focus until the pointer passes over it like a magnifying glass.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/lens-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/lens-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "split-flap": {
    name: "split-flap",
    type: "registry:ui",
    title: "Split Flap",
    description: "A departure board that flaps through its glyphs, one cell behind the last, until it lands on the value.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/split-flap.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/split-flap")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-backdrop": {
    name: "grid-backdrop",
    type: "registry:ui",
    title: "Grid Backdrop",
    description: "An SVG grid with cells that fade in and out at a deterministic, seeded scatter.",
    dependencies: [],
    registryDependencies: ["utils","use-in-viewport"],
    categories: [],
    files: [{"path":"registry/loomui/grid-backdrop.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/grid-backdrop")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "spotlight-card": {
    name: "spotlight-card",
    type: "registry:ui",
    title: "Spotlight Card",
    description: "A surface with a soft highlight that follows the pointer and fades out on leave.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/spotlight-card.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/spotlight-card")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "light-curtain": {
    name: "light-curtain",
    type: "registry:ui",
    title: "Light Curtain",
    description: "An aurora hanging from the top edge, broad bands of colour leaning across each other and falling away down the page.",
    dependencies: [],
    registryDependencies: ["utils","use-in-viewport"],
    categories: [],
    files: [{"path":"registry/loomui/light-curtain.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/light-curtain")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-beams": {
    name: "grid-beams",
    type: "registry:ui",
    title: "Grid Beams",
    description: "A ruled grid with neon beams running down random lines, fading out toward the edges.",
    dependencies: [],
    registryDependencies: ["utils","use-in-viewport"],
    categories: [],
    files: [{"path":"registry/loomui/grid-beams.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/grid-beams")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "aurora-backdrop": {
    name: "aurora-backdrop",
    type: "registry:ui",
    title: "Aurora Backdrop",
    description: "A wash of blurred colour that drifts behind content on cycles that never line up.",
    dependencies: [],
    registryDependencies: ["utils","use-in-viewport"],
    categories: [],
    files: [{"path":"registry/loomui/aurora-backdrop.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/aurora-backdrop")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "stitch-path": {
    name: "stitch-path",
    type: "registry:ui",
    title: "Stitch Path",
    description: "A running stitch sewn along an SVG path as the page scrolls, following the holes it is laid over.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/stitch-path.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/stitch-path")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "tilt-card": {
    name: "tilt-card",
    type: "registry:ui",
    title: "Tilt Card",
    description: "A surface that leans away from the pointer in 3D and settles back on leave.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/tilt-card.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/tilt-card")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "flip-card": {
    name: "flip-card",
    type: "registry:ui",
    title: "Flip Card",
    description: "A card with two faces that turns in 3D when it is clicked, controlled or on its own.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/flip-card.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/flip-card")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "hold-button": {
    name: "hold-button",
    type: "registry:ui",
    title: "Hold Button",
    description: "A button that fires only after a deliberate press and hold, with a fill sweeping across to count out the wait.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/hold-button.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/hold-button")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "ripple-button": {
    name: "ripple-button",
    type: "registry:ui",
    title: "Ripple Button",
    description: "A button that sends a circle out from wherever it was pressed, sized to reach the furthest corner.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/ripple-button.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/ripple-button")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "confetti-button": {
    name: "confetti-button",
    type: "registry:ui",
    title: "Confetti Button",
    description: "A button that throws a handful of paper into the air on press, each piece lobbed on its own arc.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/confetti-button.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/confetti-button")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "elastic-tabs": {
    name: "elastic-tabs",
    type: "registry:ui",
    title: "Elastic Tabs",
    description: "A tab group whose pill stretches to cover both tabs before it contracts onto the one you picked.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/elastic-tabs.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/elastic-tabs")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "ticket-stub": {
    name: "ticket-stub",
    type: "registry:ui",
    title: "Ticket Stub",
    description: "A card torn along a perforation, with a notch bitten out of the paper at each end of it.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/ticket-stub.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/ticket-stub")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "compare-slider": {
    name: "compare-slider",
    type: "registry:ui",
    title: "Compare Slider",
    description: "Two versions of the same frame, split by a divider you drag, or move with the arrow keys.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/compare-slider.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/compare-slider")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "sticker-peel": {
    name: "sticker-peel",
    type: "registry:ui",
    title: "Sticker Peel",
    description: "A card whose corner lifts off the page on hover, folded back over the crease to show its backing.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/sticker-peel.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/sticker-peel")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "magnetic": {
    name: "magnetic",
    type: "registry:ui",
    title: "Magnetic",
    description: "A wrapper that pulls its child toward the pointer as the pointer gets close.",
    dependencies: ["@radix-ui/react-slot"],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/magnetic.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/magnetic")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "marquee": {
    name: "marquee",
    type: "registry:ui",
    title: "Marquee",
    description: "A seamless scrolling row or column, in either direction, that pauses on hover.",
    dependencies: [],
    registryDependencies: ["utils","use-in-viewport"],
    categories: [],
    files: [{"path":"registry/loomui/marquee.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/marquee")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "reading-progress": {
    name: "reading-progress",
    type: "registry:ui",
    title: "Reading Progress",
    description: "A pinned bar that tracks how far through the page, or a chosen element, the reader is.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/reading-progress.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/reading-progress")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "testimonial-wall": {
    name: "testimonial-wall",
    type: "registry:ui",
    title: "Testimonial Wall",
    description: "Columns of quotes drifting past each other at different speeds, faded at both ends.",
    dependencies: [],
    registryDependencies: ["utils","use-in-viewport"],
    categories: [],
    files: [{"path":"registry/loomui/testimonial-wall.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/testimonial-wall")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "logo-loom": {
    name: "logo-loom",
    type: "registry:ui",
    title: "Logo Loom",
    description: "A logo row woven into place, every other mark arriving from the other side of the thread.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/logo-loom.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/logo-loom")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "iphone": {
    name: "iphone",
    type: "registry:ui",
    title: "iPhone",
    description: "A device frame drawn from the real measurements, with a screen you put anything in.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/iphone.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/iphone")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "ipad": {
    name: "ipad",
    type: "registry:ui",
    title: "iPad",
    description: "A tablet frame drawn from the real measurements, upright or on its side, with a screen you put anything in.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/ipad.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/ipad")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "macbook": {
    name: "macbook",
    type: "registry:ui",
    title: "MacBook",
    description: "A laptop frame with the camera housing cut into the display and the scoop cut into its base.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/macbook.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/macbook")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "thread-timeline": {
    name: "thread-timeline",
    type: "registry:ui",
    title: "Thread Timeline",
    description: "A timeline whose thread is sewn down the page as you read, lighting each node as it reaches it.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/thread-timeline.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/thread-timeline")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "loom-loader": {
    name: "loom-loader",
    type: "registry:ui",
    title: "Loom Loader",
    description: "Threads drawn through a frame and pulled off the far side, with a shuttle crossing them.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/loom-loader.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/loom-loader")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "loom-slider": {
    name: "loom-slider",
    type: "registry:ui",
    title: "Loom Slider",
    description: "A row of dashes where the one you are holding stands tallest, with the rise travelling the track as you drag.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/loom-slider.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/loom-slider")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "progress-ring": {
    name: "progress-ring",
    type: "registry:ui",
    title: "Progress Ring",
    description: "A circular progress ring whose value springs to its target, so a number that changes mid travel keeps the speed it already had.",
    dependencies: [],
    registryDependencies: ["utils","use-spring"],
    categories: [],
    files: [{"path":"registry/loomui/progress-ring.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/progress-ring")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "shake-field": {
    name: "shake-field",
    type: "registry:ui",
    title: "Shake Field",
    description: "A field that answers back: the control shakes to acknowledge the refusal and a message opens under it to give the reason.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/shake-field.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/shake-field")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "spool": {
    name: "spool",
    type: "registry:ui",
    title: "Spool",
    description: "A container that changes shape to fit whatever it is showing, on a spring that carries its velocity through an interruption.",
    dependencies: [],
    registryDependencies: ["utils","use-spring"],
    categories: [],
    files: [{"path":"registry/loomui/spool.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/spool")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "icon-morph": {
    name: "icon-morph",
    type: "registry:ui",
    title: "Icon Morph",
    description: "One icon that turns into another by moving its own pieces, so there is never a frame with both glyphs on screen.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/icon-morph.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/icon-morph")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "photo-stamp": {
    name: "photo-stamp",
    type: "registry:ui",
    title: "Photo Stamp",
    description: "A photo that lifts off the page at full size over a blurred backdrop, the same element the whole way.",
    dependencies: [],
    registryDependencies: ["utils","use-spring"],
    categories: [],
    files: [{"path":"registry/loomui/photo-stamp.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/photo-stamp")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "trend-stack": {
    name: "trend-stack",
    type: "registry:ui",
    title: "Trend Stack",
    description: "Stacked series under a line each, revealed left to right, with the headline and the legend following the pointer.",
    dependencies: [],
    registryDependencies: ["utils","chart-frame"],
    categories: [],
    files: [{"path":"registry/loomui/trend-stack.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/trend-stack")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "gauge-arc": {
    name: "gauge-arc",
    type: "registry:ui",
    title: "Gauge Arc",
    description: "Half a ring divided into segments, drawn one after another, with the share of whichever one is in focus in the middle.",
    dependencies: [],
    registryDependencies: ["utils","chart-frame"],
    categories: [],
    files: [{"path":"registry/loomui/gauge-arc.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/gauge-arc")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "funnel-rows": {
    name: "funnel-rows",
    type: "registry:ui",
    title: "Funnel Rows",
    description: "A funnel as a row per stage, each bar scaled to its share of the first, growing one after another.",
    dependencies: [],
    registryDependencies: ["utils","chart-frame"],
    categories: [],
    files: [{"path":"registry/loomui/funnel-rows.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/funnel-rows")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "drawer": {
    name: "drawer",
    type: "registry:ui",
    title: "Drawer",
    description: "A panel that comes in from any edge and covers most of the screen, dragged anywhere on its face to send it back out.",
    dependencies: ["@radix-ui/react-dialog"],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/drawer.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/drawer")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "shimmer-skeleton": {
    name: "shimmer-skeleton",
    type: "registry:ui",
    title: "Shimmer Skeleton",
    description: "A placeholder block with a shimmer that passes across it while the real thing loads.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/shimmer-skeleton.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/shimmer-skeleton")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "card-stack": {
    name: "card-stack",
    type: "registry:ui",
    title: "Card Stack",
    description: "Cards that pin one behind another as the page scrolls, each settling behind the next.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/card-stack.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/card-stack")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "image-trail": {
    name: "image-trail",
    type: "registry:ui",
    title: "Image Trail",
    description: "Images dropped along the pointer's path, spaced by distance travelled rather than by time.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/image-trail.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/image-trail")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "bento-grid": {
    name: "bento-grid",
    type: "registry:ui",
    title: "Bento Grid",
    description: "A grid of tiles of different sizes that arrive one after another when the grid is reached.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/bento-grid.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/bento-grid")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "terminal": {
    name: "terminal",
    type: "registry:ui",
    title: "Terminal",
    description: "A window that types its commands out and prints their output a beat later.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/terminal.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/terminal")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "unfold-list": {
    name: "unfold-list",
    type: "registry:ui",
    title: "Unfold List",
    description: "A disclosure list whose panels turn down onto the page from their top edge.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/loomui/unfold-list.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/unfold-list")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "weave-text-demo": {
    name: "weave-text-demo",
    type: "registry:example",
    title: "Weave Text Demo",
    description: "Weave Text used as a headline accent.",
    dependencies: [],
    registryDependencies: ["@loomui/weave-text"],
    categories: [],
    files: [{"path":"registry/example/weave-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/weave-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "stagger-text-demo": {
    name: "stagger-text-demo",
    type: "registry:example",
    title: "Stagger Text Demo",
    description: "A sentence revealed word by word when it scrolls into view.",
    dependencies: [],
    registryDependencies: ["@loomui/stagger-text"],
    categories: [],
    files: [{"path":"registry/example/stagger-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/stagger-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "typewriter-demo": {
    name: "typewriter-demo",
    type: "registry:example",
    title: "Typewriter Demo",
    description: "A rotating list of phrases typed into a fixed-width slot.",
    dependencies: [],
    registryDependencies: ["@loomui/typewriter"],
    categories: [],
    files: [{"path":"registry/example/typewriter-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/typewriter-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "scramble-text-demo": {
    name: "scramble-text-demo",
    type: "registry:example",
    title: "Scramble Text Demo",
    description: "A wordmark decoding out of noise on every hover.",
    dependencies: [],
    registryDependencies: ["@loomui/scramble-text"],
    categories: [],
    files: [{"path":"registry/example/scramble-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/scramble-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "count-up-demo": {
    name: "count-up-demo",
    type: "registry:example",
    title: "Count Up Demo",
    description: "Three statistics counting to their values in step.",
    dependencies: [],
    registryDependencies: ["@loomui/count-up"],
    categories: [],
    files: [{"path":"registry/example/count-up-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/count-up-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "lens-text-demo": {
    name: "lens-text-demo",
    type: "registry:example",
    title: "Lens Text Demo",
    description: "A blurred headline pulled into focus under the pointer.",
    dependencies: [],
    registryDependencies: ["@loomui/lens-text"],
    categories: [],
    files: [{"path":"registry/example/lens-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/lens-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "split-flap-demo": {
    name: "split-flap-demo",
    type: "registry:example",
    title: "Split Flap Demo",
    description: "A departure board cycling through four destinations.",
    dependencies: [],
    registryDependencies: ["@loomui/split-flap"],
    categories: [],
    files: [{"path":"registry/example/split-flap-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/split-flap-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-backdrop-demo": {
    name: "grid-backdrop-demo",
    type: "registry:example",
    title: "Grid Backdrop Demo",
    description: "A grid pulsing behind a headline.",
    dependencies: [],
    registryDependencies: ["@loomui/grid-backdrop"],
    categories: [],
    files: [{"path":"registry/example/grid-backdrop-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-backdrop-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "spotlight-card-demo": {
    name: "spotlight-card-demo",
    type: "registry:example",
    title: "Spotlight Card Demo",
    description: "Two cards lit by the pointer as it crosses them.",
    dependencies: [],
    registryDependencies: ["@loomui/spotlight-card"],
    categories: [],
    files: [{"path":"registry/example/spotlight-card-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/spotlight-card-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "light-curtain-demo": {
    name: "light-curtain-demo",
    type: "registry:example",
    title: "Light Curtain Demo",
    description: "An aurora hanging from the top of a panel, leaning across itself.",
    dependencies: [],
    registryDependencies: ["@loomui/light-curtain"],
    categories: [],
    files: [{"path":"registry/example/light-curtain-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/light-curtain-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-beams-demo": {
    name: "grid-beams-demo",
    type: "registry:example",
    title: "Grid Beams Demo",
    description: "Neon beams running down a ruled grid behind a panel of copy.",
    dependencies: [],
    registryDependencies: ["@loomui/grid-beams"],
    categories: [],
    files: [{"path":"registry/example/grid-beams-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-beams-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "aurora-backdrop-demo": {
    name: "aurora-backdrop-demo",
    type: "registry:example",
    title: "Aurora Backdrop Demo",
    description: "A drifting colour wash behind a panel of copy.",
    dependencies: [],
    registryDependencies: ["@loomui/aurora-backdrop"],
    categories: [],
    files: [{"path":"registry/example/aurora-backdrop-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/aurora-backdrop-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "stitch-path-demo": {
    name: "stitch-path-demo",
    type: "registry:example",
    title: "Stitch Path Demo",
    description: "A seam sewn between two lines of copy as the page scrolls.",
    dependencies: [],
    registryDependencies: ["@loomui/stitch-path"],
    categories: [],
    files: [{"path":"registry/example/stitch-path-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/stitch-path-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "tilt-card-demo": {
    name: "tilt-card-demo",
    type: "registry:example",
    title: "Tilt Card Demo",
    description: "A card that leans away from the pointer with a soft sheen.",
    dependencies: [],
    registryDependencies: ["@loomui/tilt-card"],
    categories: [],
    files: [{"path":"registry/example/tilt-card-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/tilt-card-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "flip-card-demo": {
    name: "flip-card-demo",
    type: "registry:example",
    title: "Flip Card Demo",
    description: "A two-by-two matching game played by turning cards over.",
    dependencies: [],
    registryDependencies: ["@loomui/flip-card"],
    categories: [],
    files: [{"path":"registry/example/flip-card-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/flip-card-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "hold-button-demo": {
    name: "hold-button-demo",
    type: "registry:example",
    title: "Hold Button Demo",
    description: "A destructive action that only goes through if you keep holding.",
    dependencies: [],
    registryDependencies: ["@loomui/hold-button"],
    categories: [],
    files: [{"path":"registry/example/hold-button-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/hold-button-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "ripple-button-demo": {
    name: "ripple-button-demo",
    type: "registry:example",
    title: "Ripple Button Demo",
    description: "Three buttons, each pressed anywhere on its face.",
    dependencies: [],
    registryDependencies: ["@loomui/ripple-button"],
    categories: [],
    files: [{"path":"registry/example/ripple-button-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/ripple-button-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "confetti-button-demo": {
    name: "confetti-button-demo",
    type: "registry:example",
    title: "Confetti Button Demo",
    description: "The same throw at three different sizes.",
    dependencies: [],
    registryDependencies: ["@loomui/confetti-button"],
    categories: [],
    files: [{"path":"registry/example/confetti-button-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/confetti-button-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "elastic-tabs-demo": {
    name: "elastic-tabs-demo",
    type: "registry:example",
    title: "Elastic Tabs Demo",
    description: "Four categories with a pill that stretches between them.",
    dependencies: [],
    registryDependencies: ["@loomui/elastic-tabs"],
    categories: [],
    files: [{"path":"registry/example/elastic-tabs-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/elastic-tabs-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "ticket-stub-demo": {
    name: "ticket-stub-demo",
    type: "registry:example",
    title: "Ticket Stub Demo",
    description: "A boarding pass torn along its perforation.",
    dependencies: [],
    registryDependencies: ["@loomui/ticket-stub"],
    categories: [],
    files: [{"path":"registry/example/ticket-stub-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/ticket-stub-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "compare-slider-demo": {
    name: "compare-slider-demo",
    type: "registry:example",
    title: "Compare Slider Demo",
    description: "A draft and a shipped page split by a divider you drag.",
    dependencies: [],
    registryDependencies: ["@loomui/compare-slider"],
    categories: [],
    files: [{"path":"registry/example/compare-slider-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/compare-slider-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "sticker-peel-demo": {
    name: "sticker-peel-demo",
    type: "registry:example",
    title: "Sticker Peel Demo",
    description: "Three stickers whose corners lift as the pointer crosses them.",
    dependencies: [],
    registryDependencies: ["@loomui/sticker-peel"],
    categories: [],
    files: [{"path":"registry/example/sticker-peel-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/sticker-peel-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "magnetic-demo": {
    name: "magnetic-demo",
    type: "registry:example",
    title: "Magnetic Demo",
    description: "A button that leans toward the pointer.",
    dependencies: [],
    registryDependencies: ["@loomui/magnetic"],
    categories: [],
    files: [{"path":"registry/example/magnetic-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/magnetic-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "marquee-demo": {
    name: "marquee-demo",
    type: "registry:example",
    title: "Marquee Demo",
    description: "A row of quote cards scrolling on a seamless loop.",
    dependencies: [],
    registryDependencies: ["@loomui/marquee"],
    categories: [],
    files: [{"path":"registry/example/marquee-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/marquee-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "reading-progress-demo": {
    name: "reading-progress-demo",
    type: "registry:example",
    title: "Reading Progress Demo",
    description: "The page-level progress bar, live at the top of the screen.",
    dependencies: [],
    registryDependencies: ["@loomui/reading-progress"],
    categories: [],
    files: [{"path":"registry/example/reading-progress-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/reading-progress-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "testimonial-wall-demo": {
    name: "testimonial-wall-demo",
    type: "registry:example",
    title: "Testimonial Wall Demo",
    description: "Nine quotes dealt across three columns going opposite ways.",
    dependencies: [],
    registryDependencies: ["@loomui/testimonial-wall"],
    categories: [],
    files: [{"path":"registry/example/testimonial-wall-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/testimonial-wall-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "logo-loom-demo": {
    name: "logo-loom-demo",
    type: "registry:example",
    title: "Logo Loom Demo",
    description: "Five wordmarks woven onto a thread as the row comes into view.",
    dependencies: [],
    registryDependencies: ["@loomui/logo-loom"],
    categories: [],
    files: [{"path":"registry/example/logo-loom-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/logo-loom-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "iphone-demo": {
    name: "iphone-demo",
    type: "registry:example",
    title: "iPhone Demo",
    description: "A device frame with a screen built out of live markup.",
    dependencies: [],
    registryDependencies: ["@loomui/iphone"],
    categories: [],
    files: [{"path":"registry/example/iphone-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/iphone-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "ipad-demo": {
    name: "ipad-demo",
    type: "registry:example",
    title: "iPad Demo",
    description: "A blank tablet held upright.",
    dependencies: [],
    registryDependencies: ["@loomui/ipad"],
    categories: [],
    files: [{"path":"registry/example/ipad-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/ipad-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "macbook-demo": {
    name: "macbook-demo",
    type: "registry:example",
    title: "MacBook Demo",
    description: "A blank laptop standing on its base.",
    dependencies: [],
    registryDependencies: ["@loomui/macbook"],
    categories: [],
    files: [{"path":"registry/example/macbook-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/macbook-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "thread-timeline-demo": {
    name: "thread-timeline-demo",
    type: "registry:example",
    title: "Thread Timeline Demo",
    description: "Four entries sewn together as the page scrolls past them.",
    dependencies: [],
    registryDependencies: ["@loomui/thread-timeline"],
    categories: [],
    files: [{"path":"registry/example/thread-timeline-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/thread-timeline-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "loom-loader-demo": {
    name: "loom-loader-demo",
    type: "registry:example",
    title: "Loom Loader Demo",
    description: "The loader at three sizes, with a wider frame on the last.",
    dependencies: [],
    registryDependencies: ["@loomui/loom-loader"],
    categories: [],
    files: [{"path":"registry/example/loom-loader-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/loom-loader-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "loom-slider-demo": {
    name: "loom-slider-demo",
    type: "registry:example",
    title: "Loom Slider Demo",
    description: "A tension control read off the dash standing tallest.",
    dependencies: [],
    registryDependencies: ["@loomui/loom-slider"],
    categories: [],
    files: [{"path":"registry/example/loom-slider-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/loom-slider-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "progress-ring-demo": {
    name: "progress-ring-demo",
    type: "registry:example",
    title: "Progress Ring Demo",
    description: "A ring stepping through five values without ever settling.",
    dependencies: [],
    registryDependencies: ["@loomui/progress-ring"],
    categories: [],
    files: [{"path":"registry/example/progress-ring-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/progress-ring-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "shake-field-demo": {
    name: "shake-field-demo",
    type: "registry:example",
    title: "Shake Field Demo",
    description: "A field that refuses an address with no @ in it, and refuses again when the same value is submitted twice.",
    dependencies: [],
    registryDependencies: ["@loomui/shake-field"],
    categories: [],
    files: [{"path":"registry/example/shake-field-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/shake-field-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "spool-demo": {
    name: "spool-demo",
    type: "registry:example",
    title: "Spool Demo",
    description: "A pill that changes shape to fit three different states, and can be interrupted part way.",
    dependencies: [],
    registryDependencies: ["@loomui/spool"],
    categories: [],
    files: [{"path":"registry/example/spool-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/spool-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "icon-morph-demo": {
    name: "icon-morph-demo",
    type: "registry:example",
    title: "Icon Morph Demo",
    description: "Five icon pairs, each one shape travelling rather than two shapes trading places.",
    dependencies: [],
    registryDependencies: ["@loomui/icon-morph"],
    categories: [],
    files: [{"path":"registry/example/icon-morph-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/icon-morph-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "photo-stamp-demo": {
    name: "photo-stamp-demo",
    type: "registry:example",
    title: "Photo Stamp Demo",
    description: "A stamp that lifts its photo out of the frame at full size over a blurred page.",
    dependencies: [],
    registryDependencies: ["@loomui/photo-stamp"],
    categories: [],
    files: [{"path":"registry/example/photo-stamp-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/photo-stamp-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "trend-stack-demo": {
    name: "trend-stack-demo",
    type: "registry:example",
    title: "Trend Stack Demo",
    description: "A year of visitors split three ways. Point at a month and the card follows.",
    dependencies: [],
    registryDependencies: ["@loomui/trend-stack"],
    categories: [],
    files: [{"path":"registry/example/trend-stack-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/trend-stack-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "gauge-arc-demo": {
    name: "gauge-arc-demo",
    type: "registry:example",
    title: "Gauge Arc Demo",
    description: "Sessions split four ways across half a ring, with the leading share in the middle.",
    dependencies: [],
    registryDependencies: ["@loomui/gauge-arc"],
    categories: [],
    files: [{"path":"registry/example/gauge-arc-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/gauge-arc-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "funnel-rows-demo": {
    name: "funnel-rows-demo",
    type: "registry:example",
    title: "Funnel Rows Demo",
    description: "A six stage pipeline, each bar as long as its share of the first.",
    dependencies: [],
    registryDependencies: ["@loomui/funnel-rows"],
    categories: [],
    files: [{"path":"registry/example/funnel-rows-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/funnel-rows-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "drawer-demo": {
    name: "drawer-demo",
    type: "registry:example",
    title: "Drawer Demo",
    description: "A drawer from the bottom edge, pulled open or swiped away by its notch.",
    dependencies: [],
    registryDependencies: ["@loomui/drawer"],
    categories: [],
    files: [{"path":"registry/example/drawer-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/drawer-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "shimmer-skeleton-demo": {
    name: "shimmer-skeleton-demo",
    type: "registry:example",
    title: "Shimmer Skeleton Demo",
    description: "A card placeholder with the sweep running down it.",
    dependencies: [],
    registryDependencies: ["@loomui/shimmer-skeleton"],
    categories: [],
    files: [{"path":"registry/example/shimmer-skeleton-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/shimmer-skeleton-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "card-stack-demo": {
    name: "card-stack-demo",
    type: "registry:example",
    title: "Card Stack Demo",
    description: "Four cards pinning one behind another inside a panel.",
    dependencies: [],
    registryDependencies: ["@loomui/card-stack"],
    categories: [],
    files: [{"path":"registry/example/card-stack-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/card-stack-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "image-trail-demo": {
    name: "image-trail-demo",
    type: "registry:example",
    title: "Image Trail Demo",
    description: "Swatches dropped behind the pointer as it crosses a panel.",
    dependencies: [],
    registryDependencies: ["@loomui/image-trail"],
    categories: [],
    files: [{"path":"registry/example/image-trail-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/image-trail-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "bento-grid-demo": {
    name: "bento-grid-demo",
    type: "registry:example",
    title: "Bento Grid Demo",
    description: "Four tiles of two sizes arriving one after another.",
    dependencies: [],
    registryDependencies: ["@loomui/bento-grid"],
    categories: [],
    files: [{"path":"registry/example/bento-grid-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/bento-grid-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "terminal-demo": {
    name: "terminal-demo",
    type: "registry:example",
    title: "Terminal Demo",
    description: "An install session typed out one command at a time.",
    dependencies: [],
    registryDependencies: ["@loomui/terminal"],
    categories: [],
    files: [{"path":"registry/example/terminal-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/terminal-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "unfold-list-demo": {
    name: "unfold-list-demo",
    type: "registry:example",
    title: "Unfold List Demo",
    description: "Three questions, one panel open at a time.",
    dependencies: [],
    registryDependencies: ["@loomui/unfold-list"],
    categories: [],
    files: [{"path":"registry/example/unfold-list-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/unfold-list-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "utils": {
    name: "utils",
    type: "registry:lib",
    title: "Utils",
    description: "The cn() class merge helper every loom component depends on.",
    dependencies: ["clsx","tailwind-merge"],
    registryDependencies: [],
    categories: [],
    files: [{"path":"registry/lib/utils.ts","type":"registry:lib","target":""}],
    component: null,
  },
  "use-spring": {
    name: "use-spring",
    type: "registry:lib",
    title: "useSpring",
    description: "A spring over named numbers, driven onto a callback rather than through state, that carries velocity across every retarget.",
    dependencies: [],
    registryDependencies: [],
    categories: [],
    files: [{"path":"registry/lib/use-spring.ts","type":"registry:lib","target":""}],
    component: null,
  },
  "chart-frame": {
    name: "chart-frame",
    type: "registry:lib",
    title: "Chart Frame",
    description: "The card every loom chart sits in: label, headline, delta, the plot, and a named tile per series.",
    dependencies: [],
    registryDependencies: ["utils"],
    categories: [],
    files: [{"path":"registry/lib/chart-frame.tsx","type":"registry:lib","target":""}],
    component: null,
  },
  "use-in-viewport": {
    name: "use-in-viewport",
    type: "registry:lib",
    title: "useInViewport",
    description: "Tells a component whether it is on screen, so a looping animation can stop while nobody is watching it.",
    dependencies: [],
    registryDependencies: [],
    categories: [],
    files: [{"path":"registry/lib/use-in-viewport.ts","type":"registry:lib","target":""}],
    component: null,
  },
}
