/* eslint-disable */
// @ts-nocheck
// AUTOGENERATED by scripts/build-registry.mts - do not edit.
import * as React from "react"

export const Index: Record<string, any> = {
  "weave-text": {
    name: "weave-text",
    type: "registry:ui",
    title: "Weave Text",
    description: "Text filled with a slow-drifting gradient, woven from a palette you control.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/weave-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/weave-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "stagger-text": {
    name: "stagger-text",
    type: "registry:ui",
    title: "Stagger Text",
    description: "Words or characters that rise into place one after another, on mount or on scroll.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/stagger-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/stagger-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "typewriter": {
    name: "typewriter",
    type: "registry:ui",
    title: "Typewriter",
    description: "Phrases typed out and deleted in a loop, with a caret and no layout shift.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/typewriter.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/typewriter")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "scramble-text": {
    name: "scramble-text",
    type: "registry:ui",
    title: "Scramble Text",
    description: "A string that resolves out of random glyphs, left to right, on mount, on scroll, or on hover.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/scramble-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/scramble-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "count-up": {
    name: "count-up",
    type: "registry:ui",
    title: "Count Up",
    description: "A number that counts to its value when it scrolls into view, without a render per frame.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/count-up.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/count-up")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "lens-text": {
    name: "lens-text",
    type: "registry:ui",
    title: "Lens Text",
    description: "Text held out of focus until the pointer passes over it like a magnifying glass.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/lens-text.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/lens-text")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "split-flap": {
    name: "split-flap",
    type: "registry:ui",
    title: "Split Flap",
    description: "A departure board that flaps through its glyphs, one cell behind the last, until it lands on the value.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/split-flap.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/split-flap")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-backdrop": {
    name: "grid-backdrop",
    type: "registry:ui",
    title: "Grid Backdrop",
    description: "An SVG grid with cells that fade in and out at a deterministic, seeded scatter.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/grid-backdrop.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/grid-backdrop")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "spotlight-card": {
    name: "spotlight-card",
    type: "registry:ui",
    title: "Spotlight Card",
    description: "A surface with a soft highlight that follows the pointer and fades out on leave.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/spotlight-card.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/spotlight-card")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-beams": {
    name: "grid-beams",
    type: "registry:ui",
    title: "Grid Beams",
    description: "A ruled grid with neon beams running down random lines, fading out toward the edges.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/grid-beams.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/grid-beams")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "aurora-backdrop": {
    name: "aurora-backdrop",
    type: "registry:ui",
    title: "Aurora Backdrop",
    description: "A wash of blurred colour that drifts behind content on cycles that never line up.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/aurora-backdrop.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/aurora-backdrop")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "stitch-path": {
    name: "stitch-path",
    type: "registry:ui",
    title: "Stitch Path",
    description: "A running stitch sewn along an SVG path as the page scrolls, following the holes it is laid over.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/stitch-path.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/stitch-path")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "tilt-card": {
    name: "tilt-card",
    type: "registry:ui",
    title: "Tilt Card",
    description: "A surface that leans away from the pointer in 3D and settles back on leave.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/tilt-card.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/tilt-card")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "flip-card": {
    name: "flip-card",
    type: "registry:ui",
    title: "Flip Card",
    description: "A card with two faces that turns in 3D when it is clicked, controlled or on its own.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/flip-card.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/flip-card")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "hold-button": {
    name: "hold-button",
    type: "registry:ui",
    title: "Hold Button",
    description: "A button that fires only after a deliberate press and hold, with a fill sweeping across to count out the wait.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/hold-button.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/hold-button")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "elastic-tabs": {
    name: "elastic-tabs",
    type: "registry:ui",
    title: "Elastic Tabs",
    description: "A tab group whose pill stretches to cover both tabs before it contracts onto the one you picked.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/elastic-tabs.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/elastic-tabs")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "ticket-stub": {
    name: "ticket-stub",
    type: "registry:ui",
    title: "Ticket Stub",
    description: "A card torn along a perforation, with a notch bitten out of the paper at each end of it.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/ticket-stub.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/ticket-stub")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "compare-slider": {
    name: "compare-slider",
    type: "registry:ui",
    title: "Compare Slider",
    description: "Two versions of the same frame, split by a divider you drag, or move with the arrow keys.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/compare-slider.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/compare-slider")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "sticker-peel": {
    name: "sticker-peel",
    type: "registry:ui",
    title: "Sticker Peel",
    description: "A card whose corner lifts off the page on hover, folded back over the crease to show its backing.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/sticker-peel.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/sticker-peel")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "magnetic": {
    name: "magnetic",
    type: "registry:ui",
    title: "Magnetic",
    description: "A wrapper that pulls its child toward the pointer as the pointer gets close.",
    dependencies: ["@radix-ui/react-slot"],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/magnetic.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/magnetic")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "marquee": {
    name: "marquee",
    type: "registry:ui",
    title: "Marquee",
    description: "A seamless scrolling row or column, in either direction, that pauses on hover.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/marquee.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/marquee")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "reading-progress": {
    name: "reading-progress",
    type: "registry:ui",
    title: "Reading Progress",
    description: "A pinned bar that tracks how far through the page, or a chosen element, the reader is.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/reading-progress.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/reading-progress")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "testimonial-wall": {
    name: "testimonial-wall",
    type: "registry:ui",
    title: "Testimonial Wall",
    description: "Columns of quotes drifting past each other at different speeds, faded at both ends.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/testimonial-wall.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/testimonial-wall")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "logo-loom": {
    name: "logo-loom",
    type: "registry:ui",
    title: "Logo Loom",
    description: "A logo row woven into place, every other mark arriving from the other side of the thread.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/logo-loom.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/logo-loom")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "iphone": {
    name: "iphone",
    type: "registry:ui",
    title: "iPhone",
    description: "A device frame drawn from the real measurements, with a screen you put anything in.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/iphone.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/iphone")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "ipad": {
    name: "ipad",
    type: "registry:ui",
    title: "iPad",
    description: "A tablet frame drawn from the real measurements, upright or on its side, with a screen you put anything in.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/ipad.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/ipad")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "macbook": {
    name: "macbook",
    type: "registry:ui",
    title: "MacBook",
    description: "A laptop frame with the camera housing cut into the display and the scoop cut into its base.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/macbook.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/macbook")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "thread-timeline": {
    name: "thread-timeline",
    type: "registry:ui",
    title: "Thread Timeline",
    description: "A timeline whose thread is sewn down the page as you read, lighting each node as it reaches it.",
    dependencies: [],
    registryDependencies: ["utils"],
    files: [{"path":"registry/loomui/thread-timeline.tsx","type":"registry:ui","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/loomui/thread-timeline")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "weave-text-demo": {
    name: "weave-text-demo",
    type: "registry:example",
    title: "Weave Text Demo",
    description: "Weave Text used as a headline accent.",
    dependencies: [],
    registryDependencies: ["@loomui/weave-text"],
    files: [{"path":"registry/example/weave-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/weave-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "stagger-text-demo": {
    name: "stagger-text-demo",
    type: "registry:example",
    title: "Stagger Text Demo",
    description: "A sentence revealed word by word when it scrolls into view.",
    dependencies: [],
    registryDependencies: ["@loomui/stagger-text"],
    files: [{"path":"registry/example/stagger-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/stagger-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "typewriter-demo": {
    name: "typewriter-demo",
    type: "registry:example",
    title: "Typewriter Demo",
    description: "A rotating list of phrases typed into a fixed-width slot.",
    dependencies: [],
    registryDependencies: ["@loomui/typewriter"],
    files: [{"path":"registry/example/typewriter-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/typewriter-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "scramble-text-demo": {
    name: "scramble-text-demo",
    type: "registry:example",
    title: "Scramble Text Demo",
    description: "A wordmark decoding out of noise on every hover.",
    dependencies: [],
    registryDependencies: ["@loomui/scramble-text"],
    files: [{"path":"registry/example/scramble-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/scramble-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "count-up-demo": {
    name: "count-up-demo",
    type: "registry:example",
    title: "Count Up Demo",
    description: "Three statistics counting to their values in step.",
    dependencies: [],
    registryDependencies: ["@loomui/count-up"],
    files: [{"path":"registry/example/count-up-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/count-up-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "lens-text-demo": {
    name: "lens-text-demo",
    type: "registry:example",
    title: "Lens Text Demo",
    description: "A blurred headline pulled into focus under the pointer.",
    dependencies: [],
    registryDependencies: ["@loomui/lens-text"],
    files: [{"path":"registry/example/lens-text-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/lens-text-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "split-flap-demo": {
    name: "split-flap-demo",
    type: "registry:example",
    title: "Split Flap Demo",
    description: "A departure board cycling through four destinations.",
    dependencies: [],
    registryDependencies: ["@loomui/split-flap"],
    files: [{"path":"registry/example/split-flap-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/split-flap-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-backdrop-demo": {
    name: "grid-backdrop-demo",
    type: "registry:example",
    title: "Grid Backdrop Demo",
    description: "A grid pulsing behind a headline.",
    dependencies: [],
    registryDependencies: ["@loomui/grid-backdrop"],
    files: [{"path":"registry/example/grid-backdrop-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-backdrop-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "spotlight-card-demo": {
    name: "spotlight-card-demo",
    type: "registry:example",
    title: "Spotlight Card Demo",
    description: "Two cards lit by the pointer as it crosses them.",
    dependencies: [],
    registryDependencies: ["@loomui/spotlight-card"],
    files: [{"path":"registry/example/spotlight-card-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/spotlight-card-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "grid-beams-demo": {
    name: "grid-beams-demo",
    type: "registry:example",
    title: "Grid Beams Demo",
    description: "Neon beams running down a ruled grid behind a panel of copy.",
    dependencies: [],
    registryDependencies: ["@loomui/grid-beams"],
    files: [{"path":"registry/example/grid-beams-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-beams-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "aurora-backdrop-demo": {
    name: "aurora-backdrop-demo",
    type: "registry:example",
    title: "Aurora Backdrop Demo",
    description: "A drifting colour wash behind a panel of copy.",
    dependencies: [],
    registryDependencies: ["@loomui/aurora-backdrop"],
    files: [{"path":"registry/example/aurora-backdrop-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/aurora-backdrop-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "stitch-path-demo": {
    name: "stitch-path-demo",
    type: "registry:example",
    title: "Stitch Path Demo",
    description: "A seam sewn between two lines of copy as the page scrolls.",
    dependencies: [],
    registryDependencies: ["@loomui/stitch-path"],
    files: [{"path":"registry/example/stitch-path-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/stitch-path-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "tilt-card-demo": {
    name: "tilt-card-demo",
    type: "registry:example",
    title: "Tilt Card Demo",
    description: "A card that leans away from the pointer with a soft sheen.",
    dependencies: [],
    registryDependencies: ["@loomui/tilt-card"],
    files: [{"path":"registry/example/tilt-card-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/tilt-card-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "flip-card-demo": {
    name: "flip-card-demo",
    type: "registry:example",
    title: "Flip Card Demo",
    description: "A two-by-two matching game played by turning cards over.",
    dependencies: [],
    registryDependencies: ["@loomui/flip-card"],
    files: [{"path":"registry/example/flip-card-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/flip-card-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "hold-button-demo": {
    name: "hold-button-demo",
    type: "registry:example",
    title: "Hold Button Demo",
    description: "A destructive action that only goes through if you keep holding.",
    dependencies: [],
    registryDependencies: ["@loomui/hold-button"],
    files: [{"path":"registry/example/hold-button-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/hold-button-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "elastic-tabs-demo": {
    name: "elastic-tabs-demo",
    type: "registry:example",
    title: "Elastic Tabs Demo",
    description: "Four categories with a pill that stretches between them.",
    dependencies: [],
    registryDependencies: ["@loomui/elastic-tabs"],
    files: [{"path":"registry/example/elastic-tabs-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/elastic-tabs-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "ticket-stub-demo": {
    name: "ticket-stub-demo",
    type: "registry:example",
    title: "Ticket Stub Demo",
    description: "A boarding pass torn along its perforation.",
    dependencies: [],
    registryDependencies: ["@loomui/ticket-stub"],
    files: [{"path":"registry/example/ticket-stub-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/ticket-stub-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "compare-slider-demo": {
    name: "compare-slider-demo",
    type: "registry:example",
    title: "Compare Slider Demo",
    description: "A draft and a shipped page split by a divider you drag.",
    dependencies: [],
    registryDependencies: ["@loomui/compare-slider"],
    files: [{"path":"registry/example/compare-slider-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/compare-slider-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "sticker-peel-demo": {
    name: "sticker-peel-demo",
    type: "registry:example",
    title: "Sticker Peel Demo",
    description: "Three stickers whose corners lift as the pointer crosses them.",
    dependencies: [],
    registryDependencies: ["@loomui/sticker-peel"],
    files: [{"path":"registry/example/sticker-peel-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/sticker-peel-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "magnetic-demo": {
    name: "magnetic-demo",
    type: "registry:example",
    title: "Magnetic Demo",
    description: "A button that leans toward the pointer.",
    dependencies: [],
    registryDependencies: ["@loomui/magnetic"],
    files: [{"path":"registry/example/magnetic-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/magnetic-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "marquee-demo": {
    name: "marquee-demo",
    type: "registry:example",
    title: "Marquee Demo",
    description: "A row of quote cards scrolling on a seamless loop.",
    dependencies: [],
    registryDependencies: ["@loomui/marquee"],
    files: [{"path":"registry/example/marquee-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/marquee-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "reading-progress-demo": {
    name: "reading-progress-demo",
    type: "registry:example",
    title: "Reading Progress Demo",
    description: "The page-level progress bar, live at the top of the screen.",
    dependencies: [],
    registryDependencies: ["@loomui/reading-progress"],
    files: [{"path":"registry/example/reading-progress-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/reading-progress-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "testimonial-wall-demo": {
    name: "testimonial-wall-demo",
    type: "registry:example",
    title: "Testimonial Wall Demo",
    description: "Nine quotes dealt across three columns going opposite ways.",
    dependencies: [],
    registryDependencies: ["@loomui/testimonial-wall"],
    files: [{"path":"registry/example/testimonial-wall-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/testimonial-wall-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "logo-loom-demo": {
    name: "logo-loom-demo",
    type: "registry:example",
    title: "Logo Loom Demo",
    description: "Five wordmarks woven onto a thread as the row comes into view.",
    dependencies: [],
    registryDependencies: ["@loomui/logo-loom"],
    files: [{"path":"registry/example/logo-loom-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/logo-loom-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "iphone-demo": {
    name: "iphone-demo",
    type: "registry:example",
    title: "iPhone Demo",
    description: "A device frame with a screen built out of live markup.",
    dependencies: [],
    registryDependencies: ["@loomui/iphone"],
    files: [{"path":"registry/example/iphone-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/iphone-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "ipad-demo": {
    name: "ipad-demo",
    type: "registry:example",
    title: "iPad Demo",
    description: "A blank tablet held upright.",
    dependencies: [],
    registryDependencies: ["@loomui/ipad"],
    files: [{"path":"registry/example/ipad-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/ipad-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "macbook-demo": {
    name: "macbook-demo",
    type: "registry:example",
    title: "MacBook Demo",
    description: "A blank laptop standing on its base.",
    dependencies: [],
    registryDependencies: ["@loomui/macbook"],
    files: [{"path":"registry/example/macbook-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/macbook-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "thread-timeline-demo": {
    name: "thread-timeline-demo",
    type: "registry:example",
    title: "Thread Timeline Demo",
    description: "Four entries sewn together as the page scrolls past them.",
    dependencies: [],
    registryDependencies: ["@loomui/thread-timeline"],
    files: [{"path":"registry/example/thread-timeline-demo.tsx","type":"registry:example","target":""}],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/thread-timeline-demo")
      const exportName =
        Object.keys(mod).find((key) => typeof mod[key] === "function") ?? "default"
      return { default: mod.default ?? mod[exportName] }
    }),
  },
  "utils": {
    name: "utils",
    type: "registry:lib",
    title: "Utils",
    description: "The cn() class merge helper every loom component depends on.",
    dependencies: ["clsx","tailwind-merge"],
    registryDependencies: [],
    files: [{"path":"registry/lib/utils.ts","type":"registry:lib","target":""}],
    component: null,
  },
}
